events {
    worker_connections 1024;
}

http {
    upstream backend_api {
        server url-shortener-1:8000;
        server url-shortener-2:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}