events {
    worker_connections 1024;
}

http {
    upstream backend_cluster {
        server url-shortener-1:8000;
        server url-shortener-2:8000;
    }

    # FRONTEND: Serves your HTML UI on standard Port 80
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }

    # BACKEND: Routes API traffic on Port 8000 to your Python workers
    server {
        listen 8000;
        location / {
            proxy_pass http://backend_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
